# Generated by Django 5.1.6 on 2025-12-24 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker_registration', '0002_alter_worker_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('mason', 'Mason'), ('painter', 'Painter'), ('driver', 'Driver'), ('welder', 'Welder'), ('loading_unloading', 'Loading & Unloading'), ('cleaning_housekeeping', 'Cleaning & Housekeeping'), ('ac_technician', 'AC Technician'), ('security_guard', 'Security Guard'), ('gardener', 'Gardener'), ('cook', 'Cook'), ('cctv_technician', 'CCTV Technician'), ('solar_panel_technician', 'Solar Panel Technician'), ('construction_helper', 'Construction Helper'), ('babysitter', 'Babysitter'), ('elder_care_assistant', 'Elder Care Assistant'), ('agricultural_worker', 'Agricultural Worker'), ('pest_control_worker', 'Pest Control Worker')], max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('problem_description', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='worker_registration.worker_registration')),
            ],
        ),
    ]
